# Generated by Django 4.1 on 2025-03-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('join_time', models.IntegerField(default=0)),
                ('draft', models.JSONField(null=True)),
            ],
        ),
    ]
